AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SecurityGroupId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Security Group ID for the Redis Cluster
    Default: /ai-code-heist/security-group-redis-id
Resources:
  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t2.micro
      Engine: redis
      EngineVersion: 7.1
      NumCacheNodes: 1
      ClusterName: ai-code-heist-redis
      VpcSecurityGroupIds:
        - !Ref SecurityGroupId
      CacheSubnetGroupName: ai-code-heist-private-sg
Outputs:
  CacheClusterId:
    Description: The ID of the Redis cluster
    Value: !Ref RedisCluster